#!/usr/bin/env bash
# refresh docs/bench/results.{csv,md} against a running broker.
#
# Usage:
#   scripts/bench/run-readme-bench.sh [BROKER_HOST:PORT]
#
# Defaults to 127.0.0.1:9092. Starts a fresh CSV each run so the committed
# snapshot reflects a consistent hardware pass.
#
# Expects `bench/build/install/bench/bin/bench` + `broker-app/.../broker-app`
# to already be installed — run `./gradlew :bench:installDist :broker-app:installDist`
# first. Expects a broker reachable at BROKER. Single-broker is fine;
# multi-broker numbers will differ.

set -euo pipefail

BROKER="${1:-127.0.0.1:9092}"
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CSV="$REPO_ROOT/docs/bench/results.csv"
MD="$REPO_ROOT/docs/bench/results.md"
BENCH="$REPO_ROOT/bench/build/install/bench/bin/bench"
ADMIN="$REPO_ROOT/broker-app/build/install/broker-app/bin/broker-app"

if [[ ! -x "$BENCH" ]]; then
    echo "bench binary not found at $BENCH — run ./gradlew :bench:installDist first" >&2
    exit 2
fi
if [[ ! -x "$ADMIN" ]]; then
    echo "broker-app binary not found at $ADMIN — run ./gradlew :broker-app:installDist first" >&2
    exit 2
fi

mkdir -p "$(dirname "$CSV")"
rm -f "$CSV"

# $MD is gitignored (repo-wide *.md rule except README.md). It's a local
# rendering users can paste into README.md's perf section on regenerate.

SIZES=(256 1024 4096)
RECORDS=5000

for size in "${SIZES[@]}"; do
    topic="bench-p${size}"
    echo "--- payload ${size}B ---"
    # Create the topic; ignore failure if it already exists (rerun case).
    "$ADMIN" topics create --broker "$BROKER" --topic "$topic" --partitions 1 --replication-factor 1 \
        >/dev/null 2>&1 || true
    "$BENCH" producer --broker "$BROKER" --topic "$topic" --partition 0 \
        --records "$RECORDS" --payload-size "$size" --csv "$CSV" \
        | grep -E "throughput|latency"
    "$BENCH" consumer --broker "$BROKER" --topic "$topic" --partition 0 \
        --records "$RECORDS" --csv "$CSV" \
        | grep -E "throughput|latency"
done

# Render a simple markdown table from the CSV so the README can embed
# it verbatim.
python3 - <<PY > "$MD"
import csv

rows = list(csv.DictReader(open("$CSV")))
# Re-key rows by (mode, bytes) — payload size is implicit in bytes/records.
producer = [r for r in rows if r["mode"] == "producer"]
consumer = [r for r in rows if r["mode"] == "consumer"]

def fmt(row):
    rec = int(row["records"])
    bytes_ = int(row["bytes"])
    payload = bytes_ // rec
    rps = float(row["records_per_s"])
    mbps = float(row["bytes_per_s"]) / (1024*1024)
    p50 = float(row["p50_us"]) / 1000  # us -> ms
    p99 = float(row["p99_us"]) / 1000
    p999 = float(row["p999_us"]) / 1000
    return f"| {payload}B | {rec:,} | {rps:,.0f} | {mbps:,.2f} | {p50:.2f}ms | {p99:.2f}ms | {p999:.2f}ms |"

print("<!-- auto-generated by scripts/bench/run-readme-bench.sh — do not edit by hand -->")
print()
print("### Producer")
print()
print("| Payload | Records | rps | MiB/s | p50 | p99 | p999 |")
print("|---|---|---|---|---|---|---|")
for r in producer:
    print(fmt(r))
print()
print("### Consumer")
print()
print("| Payload | Records | rps | MiB/s | p50 | p99 | p999 |")
print("|---|---|---|---|---|---|---|")
for r in consumer:
    print(fmt(r))
PY

echo
echo "--- docs/bench/results.md ---"
cat "$MD"
